### ISSUE TITLE
 Check if Redis HTTP Cache is active

### ISSUE THREAD

**Issue by christopherholst** [FriendsOfShopware/FroshFasterCacheManager#1]
`if (!$this->checkCacheDir($cacheDir)) {
                return;
            }`
in /Bundle/CacheManager.php Row: 25

If the html folder does not exist in the cache, you could check it here on redis http cache and then delete it by "redis-cli flushall" ?

**Comment by tinect** [comment]
Thank you. Will have a look into this next days. :-)

**Comment by shyim** [comment]
Do you really need this plugin when u use already redis http cache? Does the redis plugin not that already?

**Comment by christopherholst** [comment]
If you use Redis with HTTP Cache, even without this plugin, the cache will not be deleted by Redis via Shopware. You always have to do this manually via the SSH console. Unfortunately.

**Comment by tinect** [comment]
Thank you @shyim. 
@snHolst as shyim mentioned, I'd suggest an other way. It'll be possible to add a event, where you could subscribe and doing your stuff.

I don't see any need to fix/extend some enterprise features. Or you could ask for fixing it on shopware side.

Should I add some events, where you can subscribe?
